Bugfix requests_mock_assertion if body is empty
Don't try to deserialize when the request body is None.

Fix errors like:
```
Traceback (most recent call last):
File "bx_py_utils/bx_py_utils_tests/tests/test_requests_mock_assertion.py", line 129, in
test_assert_json_requests_mock_with_none
    assert_json_requests_mock(mock=m, data=[{'request': 'GET http://test.tld/'}])
File "bx_py_utils/bx_py_utils/test_utils/requests_mock_assertion.py", line 44, in
assert_json_requests_mock
    history = build_requests_mock_history(mock, only_json=True)
File "bx_py_utils/bx_py_utils/test_utils/requests_mock_assertion.py", line 16, in
build_requests_mock_history
    json_data = request.json()
  File "bx_py_utils/.venv/lib/python3.10/site-packages/requests_mock/request.py", line 155, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```